# Generated by Django 5.2 on 2025-08-02 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lawyers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('legal_category', models.CharField(blank=True, max_length=100, verbose_name='Legal Category')),
                ('case_description', models.TextField(verbose_name='Case Description')),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Estimated Budget')),
                ('urgency', models.CharField(default='medium', max_length=20, verbose_name='Urgency')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('lost', 'Lost'), ('spam', 'Spam')], default='new', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20, verbose_name='Priority')),
                ('source', models.CharField(choices=[('website_form', 'Website Contact Form'), ('chatbot', 'AI Chatbot'), ('phone', 'Phone Call'), ('email', 'Email'), ('referral', 'Referral'), ('social_media', 'Social Media'), ('google_ads', 'Google Ads'), ('other', 'Other')], default='website_form', max_length=30, verbose_name='Source')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('referrer_url', models.URLField(blank=True, verbose_name='Referrer URL')),
                ('utm_source', models.CharField(blank=True, max_length=100, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, max_length=100, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=100, verbose_name='UTM Campaign')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Internal Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True, verbose_name='First Contact Date')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='lawyers.lawyer')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField(verbose_name='Scheduled Time')),
                ('duration_minutes', models.PositiveIntegerField(choices=[(15, '15 minutes'), (30, '30 minutes'), (45, '45 minutes'), (60, '1 hour'), (90, '1.5 hours'), (120, '2 hours')], default=30, verbose_name='Duration (minutes)')),
                ('consultation_type', models.CharField(choices=[('free', 'Free Consultation'), ('paid', 'Paid Consultation'), ('follow_up', 'Follow-up'), ('emergency', 'Emergency')], default='free', max_length=20, verbose_name='Type')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20, verbose_name='Status')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Fee')),
                ('meeting_method', models.CharField(choices=[('in_person', 'In Person'), ('phone', 'Phone Call'), ('video', 'Video Call'), ('zoom', 'Zoom')], default='in_person', max_length=20, verbose_name='Meeting Method')),
                ('meeting_link', models.URLField(blank=True, verbose_name='Meeting Link')),
                ('location', models.TextField(blank=True, verbose_name='Location')),
                ('agenda', models.TextField(blank=True, verbose_name='Agenda')),
                ('client_questions', models.TextField(blank=True, verbose_name='Client Questions')),
                ('lawyer_notes', models.TextField(blank=True, verbose_name='Lawyer Notes')),
                ('outcome', models.TextField(blank=True, verbose_name='Outcome')),
                ('follow_up_required', models.BooleanField(default=False, verbose_name='Follow-up Required')),
                ('follow_up_date', models.DateField(blank=True, null=True, verbose_name='Follow-up Date')),
                ('follow_up_notes', models.TextField(blank=True, verbose_name='Follow-up Notes')),
                ('confirmation_sent', models.BooleanField(default=False, verbose_name='Confirmation Sent')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Reminder Sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='lawyers.lawyer')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('sms', 'SMS'), ('general', 'General Note')], default='general', max_length=20, verbose_name='Note Type')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('is_client_communication', models.BooleanField(default=False, verbose_name='Client Communication')),
                ('communication_successful', models.BooleanField(default=True, verbose_name='Communication Successful')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_notes', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Lead Note',
                'verbose_name_plural': 'Lead Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('new_leads', models.PositiveIntegerField(default=0, verbose_name='New Leads')),
                ('total_leads', models.PositiveIntegerField(default=0, verbose_name='Total Leads')),
                ('qualified_leads', models.PositiveIntegerField(default=0, verbose_name='Qualified Leads')),
                ('converted_leads', models.PositiveIntegerField(default=0, verbose_name='Converted Leads')),
                ('lost_leads', models.PositiveIntegerField(default=0, verbose_name='Lost Leads')),
                ('consultations_scheduled', models.PositiveIntegerField(default=0, verbose_name='Consultations Scheduled')),
                ('consultations_completed', models.PositiveIntegerField(default=0, verbose_name='Consultations Completed')),
                ('consultations_cancelled', models.PositiveIntegerField(default=0, verbose_name='Consultations Cancelled')),
                ('lead_to_consultation_rate', models.FloatField(default=0, verbose_name='Lead to Consultation Rate')),
                ('consultation_to_client_rate', models.FloatField(default=0, verbose_name='Consultation to Client Rate')),
                ('top_lead_sources', models.JSONField(blank=True, default=list, verbose_name='Top Lead Sources')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_analytics', to='lawyers.lawyer')),
            ],
            options={
                'verbose_name': 'Lead Analytics',
                'verbose_name_plural': 'Lead Analytics',
                'ordering': ['-date'],
                'unique_together': {('lawyer', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Source Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('cost_per_lead', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost per Lead')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_sources', to='lawyers.lawyer')),
            ],
            options={
                'verbose_name': 'Lead Source',
                'verbose_name_plural': 'Lead Sources',
                'unique_together': {('lawyer', 'name')},
            },
        ),
    ]
