# Generated by Django 5.2 on 2025-08-02 16:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lawyers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_model', models.CharField(default='deepseek-chat', max_length=50, verbose_name='AI Model')),
                ('system_prompt', models.TextField(help_text='Instructions for the AI assistant', verbose_name='System Prompt')),
                ('max_tokens', models.PositiveIntegerField(default=500, verbose_name='Max Tokens')),
                ('temperature', models.FloatField(default=0.7, verbose_name='Temperature')),
                ('collect_contact_info', models.BooleanField(default=True, verbose_name='Collect Contact Info')),
                ('auto_suggest_consultation', models.BooleanField(default=True, verbose_name='Auto Suggest Consultation')),
                ('response_delay_seconds', models.PositiveIntegerField(default=1, verbose_name='Response Delay (seconds)')),
                ('welcome_message_ru', models.TextField(blank=True, verbose_name='Welcome Message (Russian)')),
                ('welcome_message_ky', models.TextField(blank=True, verbose_name='Welcome Message (Kyrgyz)')),
                ('welcome_message_en', models.TextField(blank=True, verbose_name='Welcome Message (English)')),
                ('office_hours_enabled', models.BooleanField(default=True, verbose_name='Office Hours Enabled')),
                ('office_hours', models.JSONField(blank=True, default=dict, verbose_name='Office Hours')),
                ('offline_message', models.TextField(blank=True, verbose_name='Offline Message')),
                ('legal_disclaimer', models.TextField(default='This chat provides general legal information only and does not constitute legal advice.', verbose_name='Legal Disclaimer')),
                ('show_disclaimer', models.BooleanField(default=True, verbose_name='Show Disclaimer')),
                ('track_analytics', models.BooleanField(default=True, verbose_name='Track Analytics')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lawyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_config', to='lawyers.lawyer')),
            ],
            options={
                'verbose_name': 'Chat Configuration',
                'verbose_name_plural': 'Chat Configurations',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Session ID')),
                ('visitor_name', models.CharField(blank=True, max_length=100, verbose_name='Visitor Name')),
                ('visitor_email', models.EmailField(blank=True, max_length=254, verbose_name='Visitor Email')),
                ('visitor_phone', models.CharField(blank=True, max_length=20, verbose_name='Visitor Phone')),
                ('visitor_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Visitor IP')),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('transferred', 'Transferred to Lawyer')], default='active', max_length=20, verbose_name='Status')),
                ('language', models.CharField(default='ru', max_length=5, verbose_name='Language')),
                ('legal_category', models.CharField(blank=True, max_length=50, verbose_name='Legal Category')),
                ('consultation_requested', models.BooleanField(default=False, verbose_name='Consultation Requested')),
                ('consultation_message', models.TextField(blank=True, verbose_name='Consultation Message')),
                ('preferred_contact_method', models.CharField(blank=True, choices=[('phone', 'Phone'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=20, verbose_name='Preferred Contact Method')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('referrer', models.URLField(blank=True, verbose_name='Referrer')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='lawyers.lawyer')),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('ai', 'AI Response'), ('system', 'System Message'), ('lawyer', 'Lawyer Message')], max_length=10, verbose_name='Message Type')),
                ('content', models.TextField(verbose_name='Message Content')),
                ('ai_model', models.CharField(blank=True, max_length=50, verbose_name='AI Model')),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Response Time (ms)')),
                ('tokens_used', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tokens Used')),
                ('is_helpful', models.BooleanField(default=False, verbose_name='Marked as Helpful')),
                ('needs_review', models.BooleanField(default=False, verbose_name='Needs Review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], verbose_name='Rating')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('would_recommend', models.BooleanField(default=True, verbose_name='Would Recommend')),
                ('helpfulness', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], null=True, verbose_name='Helpfulness')),
                ('response_quality', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], null=True, verbose_name='Response Quality')),
                ('ease_of_use', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], null=True, verbose_name='Ease of Use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chatbot.chatsession')),
            ],
            options={
                'verbose_name': 'Chat Feedback',
                'verbose_name_plural': 'Chat Feedback',
            },
        ),
        migrations.CreateModel(
            name='ChatAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('total_sessions', models.PositiveIntegerField(default=0, verbose_name='Total Sessions')),
                ('completed_sessions', models.PositiveIntegerField(default=0, verbose_name='Completed Sessions')),
                ('abandoned_sessions', models.PositiveIntegerField(default=0, verbose_name='Abandoned Sessions')),
                ('total_messages', models.PositiveIntegerField(default=0, verbose_name='Total Messages')),
                ('avg_messages_per_session', models.FloatField(default=0, verbose_name='Avg Messages per Session')),
                ('avg_response_time_ms', models.PositiveIntegerField(default=0, verbose_name='Avg Response Time (ms)')),
                ('leads_generated', models.PositiveIntegerField(default=0, verbose_name='Leads Generated')),
                ('consultation_requests', models.PositiveIntegerField(default=0, verbose_name='Consultation Requests')),
                ('conversion_rate', models.FloatField(default=0, verbose_name='Conversion Rate')),
                ('avg_rating', models.FloatField(default=0, verbose_name='Average Rating')),
                ('total_feedback', models.PositiveIntegerField(default=0, verbose_name='Total Feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_analytics', to='lawyers.lawyer')),
            ],
            options={
                'verbose_name': 'Chat Analytics',
                'verbose_name_plural': 'Chat Analytics',
                'ordering': ['-date'],
                'unique_together': {('lawyer', 'date')},
            },
        ),
    ]
