# Generated by Django 5.2 on 2025-08-02 16:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LawFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Firm Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('logo', models.ImageField(blank=True, upload_to='firm_logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])], verbose_name='Logo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Law Firm',
                'verbose_name_plural': 'Law Firms',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('basic', 'Basic - $50/month'), ('pro', 'Pro - $150/month'), ('premium', 'Premium - $300/month')], default='basic', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('trial', 'Trial')], default='trial', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('bio', models.TextField(blank=True, verbose_name='Biography')),
                ('photo', models.ImageField(blank=True, upload_to='lawyer_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Photo')),
                ('specialties', models.JSONField(default=list, help_text='List of legal specialties', verbose_name='Specialties')),
                ('license_number', models.CharField(blank=True, max_length=50, verbose_name='License Number')),
                ('years_experience', models.PositiveIntegerField(default=0, verbose_name='Years of Experience')),
                ('website_theme', models.CharField(choices=[('blue', 'Professional Blue'), ('navy', 'Navy Corporate'), ('gray', 'Modern Gray'), ('dark', 'Dark Professional')], default='blue', max_length=20, verbose_name='Website Theme')),
                ('primary_language', models.CharField(choices=[('ru', 'Russian'), ('ky', 'Kyrgyz'), ('en', 'English')], default='ru', max_length=5, verbose_name='Primary Language')),
                ('domain_slug', models.SlugField(max_length=100, unique=True, verbose_name='Website URL')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Consultation Fee')),
                ('office_hours', models.JSONField(blank=True, default=dict, verbose_name='Office Hours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lawyers.lawfirm')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_profile', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lawyers.subscription')),
            ],
            options={
                'verbose_name': 'Lawyer',
                'verbose_name_plural': 'Lawyers',
            },
        ),
    ]
