# Generated by Django 5.2 on 2025-08-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawfirm',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='website',
        ),
        migrations.RemoveField(
            model_name='lawyer',
            name='phone',
        ),
        migrations.AddField(
            model_name='lawyer',
            name='website_published',
            field=models.BooleanField(default=False, verbose_name='Website Published'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Expires At'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan_type',
            field=models.CharField(choices=[('basic', 'Basic - $50/month'), ('pro', 'Pro - $150/month'), ('premium', 'Premium - $300/month')], default='basic', max_length=20, verbose_name='Plan Type'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='starts_at',
            field=models.DateTimeField(verbose_name='Starts At'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('trial', 'Trial')], default='trial', max_length=20, verbose_name='Status'),
        ),
    ]
