# Generated by Django 5.2 on 2025-08-02 16:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lawyers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Template Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('thumbnail', models.ImageField(upload_to='template_thumbnails/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Template Thumbnail')),
                ('template_data', models.JSONField(default=dict, verbose_name='Template Data')),
                ('specialties', models.JSONField(blank=True, default=list, verbose_name='Suitable Specialties')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium Template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Template',
                'verbose_name_plural': 'Website Templates',
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Website Title')),
                ('meta_description', models.TextField(blank=True, max_length=160, verbose_name='Meta Description')),
                ('domain_slug', models.SlugField(max_length=100, unique=True, verbose_name='Domain Slug')),
                ('custom_domain', models.CharField(blank=True, max_length=100, verbose_name='Custom Domain')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('content_data', models.JSONField(default=dict, verbose_name='Content Data')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='Google Analytics ID')),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=50, verbose_name='Facebook Pixel ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('lawyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website', to='lawyers.lawyer')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website_builder.websitetemplate')),
            ],
            options={
                'verbose_name': 'Website',
                'verbose_name_plural': 'Websites',
            },
        ),
        migrations.CreateModel(
            name='WebsiteAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('logo', 'Logo'), ('favicon', 'Favicon')], max_length=20, verbose_name='Asset Type')),
                ('name', models.CharField(max_length=200, verbose_name='Asset Name')),
                ('file', models.FileField(upload_to='website_assets/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'pdf', 'doc', 'docx', 'txt'])], verbose_name='File')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt Text')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='website_builder.website')),
            ],
            options={
                'verbose_name': 'Website Asset',
                'verbose_name_plural': 'Website Assets',
            },
        ),
        migrations.CreateModel(
            name='WebsiteAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('page_views', models.PositiveIntegerField(default=0, verbose_name='Page Views')),
                ('unique_visitors', models.PositiveIntegerField(default=0, verbose_name='Unique Visitors')),
                ('bounce_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Bounce Rate')),
                ('avg_session_duration', models.DurationField(blank=True, null=True, verbose_name='Average Session Duration')),
                ('popular_pages', models.JSONField(blank=True, default=list, verbose_name='Popular Pages')),
                ('traffic_sources', models.JSONField(blank=True, default=dict, verbose_name='Traffic Sources')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='website_builder.website')),
            ],
            options={
                'verbose_name': 'Website Analytics',
                'verbose_name_plural': 'Website Analytics',
                'ordering': ['-date'],
                'unique_together': {('website', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WebsitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('services', 'Services'), ('contact', 'Contact'), ('blog', 'Blog'), ('privacy', 'Privacy Policy'), ('terms', 'Terms of Service'), ('custom', 'Custom Page')], max_length=20, verbose_name='Page Type')),
                ('title', models.CharField(max_length=200, verbose_name='Page Title')),
                ('slug', models.SlugField(max_length=100, verbose_name='Page Slug')),
                ('content', models.JSONField(default=dict, verbose_name='Page Content')),
                ('meta_description', models.TextField(blank=True, max_length=160, verbose_name='Meta Description')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='website_builder.website')),
            ],
            options={
                'verbose_name': 'Website Page',
                'verbose_name_plural': 'Website Pages',
                'ordering': ['order', 'title'],
                'unique_together': {('website', 'slug')},
            },
        ),
    ]
